
/**
 * libemulation
 * Apple II MMU Interface
 * (C) 2010-2011 by Marc S. Ressl (mressl@umich.edu)
 * Released under the GPL
 *
 * Defines the Apple II MMU interface
 */

#ifndef _APPLEIIMMUINTERFACE_H
#define _APPLEIIMMUINTERFACE_H

typedef enum
{
	APPLEIIMMU_MAP_MEMORY,
    APPLEIIMMU_UNMAP_MEMORY,
    APPLEIIMMU_MAP_SLOT0_IO,
    APPLEIIMMU_MAP_SLOT1_IO,
    APPLEIIMMU_MAP_SLOT2_IO,
    APPLEIIMMU_MAP_SLOT3_IO,
    APPLEIIMMU_MAP_SLOT4_IO,
    APPLEIIMMU_MAP_SLOT5_IO,
    APPLEIIMMU_MAP_SLOT6_IO,
    APPLEIIMMU_MAP_SLOT7_IO,
    APPLEIIMMU_UNMAP_SLOT0_IO,
    APPLEIIMMU_UNMAP_SLOT1_IO,
    APPLEIIMMU_UNMAP_SLOT2_IO,
    APPLEIIMMU_UNMAP_SLOT3_IO,
    APPLEIIMMU_UNMAP_SLOT4_IO,
    APPLEIIMMU_UNMAP_SLOT5_IO,
    APPLEIIMMU_UNMAP_SLOT6_IO,
    APPLEIIMMU_UNMAP_SLOT7_IO,
    APPLEIIMMU_MAP_SLOT1_MEMORY,
    APPLEIIMMU_MAP_SLOT2_MEMORY,
    APPLEIIMMU_MAP_SLOT3_MEMORY,
    APPLEIIMMU_MAP_SLOT4_MEMORY,
    APPLEIIMMU_MAP_SLOT5_MEMORY,
    APPLEIIMMU_MAP_SLOT6_MEMORY,
    APPLEIIMMU_MAP_SLOT7_MEMORY,
    APPLEIIMMU_UNMAP_SLOT1_MEMORY,
    APPLEIIMMU_UNMAP_SLOT2_MEMORY,
    APPLEIIMMU_UNMAP_SLOT3_MEMORY,
    APPLEIIMMU_UNMAP_SLOT4_MEMORY,
    APPLEIIMMU_UNMAP_SLOT5_MEMORY,
    APPLEIIMMU_UNMAP_SLOT6_MEMORY,
    APPLEIIMMU_UNMAP_SLOT7_MEMORY,
} AppleIIMMUMessage;

typedef enum
{
    APPLEIIVIDEO_SET_TEXT1MEMORY,
    APPLEIIVIDEO_SET_TEXT2MEMORY,
    APPLEIIVIDEO_SET_HIRES1MEMORY,
    APPLEIIVIDEO_SET_HIRES2MEMORY,
} AppleIIVideoMessage;

typedef enum
{
	APPLEIIGAMEPORT_SET_PDL0,
	APPLEIIGAMEPORT_SET_PDL1,
	APPLEIIGAMEPORT_SET_PDL2,
	APPLEIIGAMEPORT_SET_PDL3,
	APPLEIIGAMEPORT_SET_PB0,
	APPLEIIGAMEPORT_SET_PB1,
	APPLEIIGAMEPORT_SET_PB2,
    APPLEIIGAMEPORT_GET_AN0,
    APPLEIIGAMEPORT_GET_AN1,
    APPLEIIGAMEPORT_GET_AN2,
    APPLEIIGAMEPORT_GET_AN3,
} AppleIIGamePortMessage;

typedef enum
{
    APPLEIIGAMEPORT_DID_STROBE,
    APPLEIIGAMEPORT_AN0_DID_CHANGE,
    APPLEIIGAMEPORT_AN1_DID_CHANGE,
    APPLEIIGAMEPORT_AN2_DID_CHANGE,
    APPLEIIGAMEPORT_AN3_DID_CHANGE,
} AppleIIGamePortNotification;

#endif
