
/**
 * libemulation
 * Control Bus Interface
 * (C) 2010 by Marc S. Ressl (mressl@umich.edu)
 * Released under the GPL
 *
 * Defines the control bus interface
 */

typedef enum
{
	CONTROLBUS_SET_POWERSTATE,
	CONTROLBUS_GET_POWERSTATE,
	CONTROLBUS_SET_RESET,
	CONTROLBUS_SET_IRQ,
	CONTROLBUS_SET_NMI,
	CONTROLBUS_SCHEDULE,
	CONTROLBUS_DESCHEDULE,
	CONTROLBUS_GET_CLOCKCYCLE,
	CONTROLBUS_ADD_CLOCKCYCLE,
	CONTROLBUS_GET_AUDIOBUFFERINDEX,
	CONTROLBUS_REQUEST_BUS,
	CONTROLBUS_RELEASE_BUS,
} ControlBusMessages;

typedef enum
{
	CONTROLBUS_POWERSTATE_CHANGED,
	CONTROLBUS_RESET_CHANGED,
	CONTROLBUS_IRQ_CHANGED,
	CONTROLBUS_NMI_CHANGED,
	CONTROLBUS_SCHEDULER_FIRED,
} ControlBusNotifications;

typedef enum
{
	CONTROLBUS_POWERSTATE_ON,
	CONTROLBUS_POWERSTATE_PAUSE,
	CONTROLBUS_POWERSTATE_STANDBY,
	CONTROLBUS_POWERSTATE_SLEEP,
	CONTROLBUS_POWERSTATE_HIBERNATE,
	CONTROLBUS_POWERSTATE_OFF,
} ControlBusPowerStates;
