
/**
 * libemulation
 * Control Bus Interface
 * (C) 2010 by Marc S. Ressl (mressl@umich.edu)
 * Released under the GPL
 *
 * Defines the control bus interface
 */

// Messages
enum
{
	CONTROLBUS_SET_POWERSTATE,
	CONTROLBUS_GET_POWERSTATE,
	CONTROLBUS_SET_RESET,
	CONTROLBUS_SET_IRQ,
	CONTROLBUS_SET_IRQ0,
	CONTROLBUS_SET_IRQ1,
	CONTROLBUS_SET_IRQ2,
	CONTROLBUS_SET_IRQ3,
	CONTROLBUS_SET_IRQ4,
	CONTROLBUS_SET_IRQ5,
	CONTROLBUS_SET_IRQ6,
	CONTROLBUS_SET_IRQ7,
	CONTROLBUS_SET_IRQ8,
	CONTROLBUS_SET_IRQ9,
	CONTROLBUS_SET_IRQ10,
	CONTROLBUS_SET_IRQ11,
	CONTROLBUS_SET_IRQ12,
	CONTROLBUS_SET_IRQ13,
	CONTROLBUS_SET_IRQ14,
	CONTROLBUS_SET_IRQ15,
	CONTROLBUS_SET_NMI,
	CONTROLBUS_ADD_TIMER,
	CONTROLBUS_REMOVE_TIMER,
	CONTROLBUS_GET_CYCLE,
	CONTROLBUS_GET_AUDIO_BUFFER_INDEX,
	CONTROLBUS_REQUEST_BUS,
	CONTROLBUS_RELEASE_BUS,
};

// Notifications
enum
{
	CONTROLBUS_POWERSTATE_CHANGED,
	CONTROLBUS_RESET_CHANGED,
	CONTROLBUS_IRQ_CHANGED,
	CONTROLBUS_NMI_CHANGED,
};

// Power states
enum
{
	CONTROLBUS_POWERSTATE_ON,
	CONTROLBUS_POWERSTATE_PAUSE,
	CONTROLBUS_POWERSTATE_STANDBY,
	CONTROLBUS_POWERSTATE_SLEEP,
	CONTROLBUS_POWERSTATE_HIBERNATE,
	CONTROLBUS_POWERSTATE_OFF,
};

typedef struct
{
	int cyclesLeft;
	OEComponent *component;
	int event;
} ControlBusTimer;
