
/**
 * libemulation
 * Control Bus Interface
 * (C) 2010-2011 by Marc S. Ressl (mressl@umich.edu)
 * Released under the GPL
 *
 * Defines the control bus interface
 */

#ifndef _CONTROLBUSINTERFACE_H
#define _CONTROLBUSINTERFACE_H

typedef enum
{
    CONTROLBUS_SET_POWERSTATE,
    CONTROLBUS_GET_POWERSTATE,
    
    CONTROLBUS_ASSERT_RESET,
    CONTROLBUS_CLEAR_RESET,
    CONTROLBUS_ASSERT_IRQ,
    CONTROLBUS_CLEAR_IRQ,
    CONTROLBUS_ASSERT_NMI,
    CONTROLBUS_CLEAR_NMI,
    CONTROLBUS_IS_RESET_ASSERTED,
    CONTROLBUS_IS_IRQ_ASSERTED,
    CONTROLBUS_IS_NMI_ASSERTED,
    
    CONTROLBUS_SET_CLOCKFREQUENCY,
    CONTROLBUS_GET_CLOCKFREQUENCY,
    
    CONTROLBUS_GET_CYCLECOUNT,
    CONTROLBUS_GET_AUDIOBUFFERINDEX,
    
    CONTROLBUS_SCHEDULE_TIMER,
    CONTROLBUS_CLEAR_TIMERS,
    
    CONTROLBUS_SET_CPUCLOCKMULTIPLIER,
} ControlBusMessage;

typedef enum
{
    CONTROLBUS_POWERSTATE_DID_CHANGE,
    
    CONTROLBUS_RESET_DID_ASSERT,
    CONTROLBUS_RESET_DID_CLEAR,
    CONTROLBUS_IRQ_DID_ASSERT,
    CONTROLBUS_IRQ_DID_CLEAR,
    CONTROLBUS_NMI_DID_ASSERT,
    CONTROLBUS_NMI_DID_CLEAR,
    
    CONTROLBUS_TIMER_DID_FIRE,
} ControlBusNotification;

typedef enum
{
    CONTROLBUS_POWERSTATE_ON,
    CONTROLBUS_POWERSTATE_PAUSE,
    CONTROLBUS_POWERSTATE_STANDBY,
    CONTROLBUS_POWERSTATE_SLEEP,
    CONTROLBUS_POWERSTATE_HIBERNATE,
    CONTROLBUS_POWERSTATE_OFF,
} ControlBusPowerState;

#endif
