# libemulation/definitions.cmake - Definitions of source files and include directories.
add_library(emulation
  ${LIBEMULATION_DIR}/Core/OECommon.cpp
  ${LIBEMULATION_DIR}/Core/OEComponent.cpp
  ${LIBEMULATION_DIR}/Core/OEComponentFactory.cpp
  ${LIBEMULATION_DIR}/Core/OEDevice.cpp
  ${LIBEMULATION_DIR}/Core/OEDocument.cpp
  ${LIBEMULATION_DIR}/Core/OEEmulation.cpp
  ${LIBEMULATION_DIR}/Core/OEImage.cpp
  ${LIBEMULATION_DIR}/Core/OEPackage.cpp
  ${LIBEMULATION_DIR}/Core/OESound.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/Apple1ACI.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/Apple1IO.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/Apple1Terminal.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleDiskDrive525.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleDiskIIInterfaceCard.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleGraphicsTablet.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleGraphicsTabletInterfaceCard.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIAddressDecoder.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIAudioIn.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIAudioOut.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIDisableC800.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIFloatingBus.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIGamePort.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIKeyboard.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIISlotController.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIISystemControl.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIVideo.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIIAddressDecoder.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIIBeeper.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIIDiskIO.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIIGamePort.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIIKeyboard.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIIMOS6502.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIIRTC.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIISystemControl.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleIIIVideo.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleSilentype.cpp
  ${LIBEMULATION_DIR}/Implementation/Apple/AppleSilentypeInterfaceCard.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/AddressDecoder.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/AddressMapper.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/AddressMasker.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/AddressMux.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/AddressOffset.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/ATAController.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/ATADevice.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/Audio1Bit.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/AudioCodec.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/AudioPlayer.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/ControlBus.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/FloatingBus.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/JoystickMapper.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/Monitor.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/Proxy.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/RAM.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/ROM.cpp
  ${LIBEMULATION_DIR}/Implementation/Generic/VRAM.cpp
  ${LIBEMULATION_DIR}/Implementation/MOS/MOS6502.cpp
  #${LIBEMULATION_DIR}/Implementation/MOS/MOS6509.cpp
  ${LIBEMULATION_DIR}/Implementation/MOS/MOS6522.cpp
  ${LIBEMULATION_DIR}/Implementation/MOS/MOS6530.cpp
  ${LIBEMULATION_DIR}/Implementation/MOS/MOSKIM1IO.cpp
  ${LIBEMULATION_DIR}/Implementation/MOS/MOSKIM1PLL.cpp
  ${LIBEMULATION_DIR}/Implementation/Motorola/MC6821.cpp
  ${LIBEMULATION_DIR}/Implementation/Motorola/MC6845.cpp
  ${LIBEMULATION_DIR}/Implementation/National/MM58167.cpp
  ${LIBEMULATION_DIR}/Implementation/RD/RDCFFA.cpp
  #${LIBEMULATION_DIR}/Implementation/Ricoh/RP2A03.cpp
  ${LIBEMULATION_DIR}/Implementation/Videx/VidexVideoterm.cpp
  ${LIBEMULATION_DIR}/Implementation/WDC/W65C02S.cpp
  ${LIBEMULATION_DIR}/Implementation/WDC/W65C816S.cpp
  #${LIBEMULATION_DIR}/Implementation/Zilog/Z80.cpp
)

set(LIBEMULATION_INCLUDE_DIRS
  ${LIBEMULATION_DIR}
  ${LIBEMULATION_DIR}/Core
  ${LIBEMULATION_DIR}/Interface/Apple
  ${LIBEMULATION_DIR}/Interface/EIA
  ${LIBEMULATION_DIR}/Interface/Generic
  ${LIBEMULATION_DIR}/Interface/Host
  ${LIBEMULATION_DIR}/Interface/IEEE
  ${LIBEMULATION_DIR}/Implementation/Apple
  ${LIBEMULATION_DIR}/Implementation/Generic
  ${LIBEMULATION_DIR}/Implementation/MOS
  ${LIBEMULATION_DIR}/Implementation/Motorola
  ${LIBEMULATION_DIR}/Implementation/National
  ${LIBEMULATION_DIR}/Implementation/RD
  ${LIBEMULATION_DIR}/Implementation/Ricoh
  ${LIBEMULATION_DIR}/Implementation/Videx
  ${LIBEMULATION_DIR}/Implementation/WDC
  ${LIBEMULATION_DIR}/Implementation/Zilog)
